### ISSUE TITLE
Размеры поля

### ISSUE THREAD

**Issue by vadimsemenov** [IFMO-MobDev-2014/lesson1#1]
> Размер игрового поля - 240x320, отображение необходимо растянуть на весь экран.

В коде используется соотношение w/4 x h/4, где w и h -- размеры видимой части.

Уточните, пожалуйста, что нужно сделать.

**Comment by thevery** [comment]
Smaller size is used in "sample" to achieve more FPS.
You should use 320*240 scaled to whole screen in "real" app.
