### ISSUE TITLE
значение слова "растянуть"

### ISSUE THREAD

**Issue by gerra** [IFMO-MobDev-2014/lesson1#25]
"Размер игрового поля - 240x320, отображение необходимо растянуть на весь экран". По коду одна клетка занимает 4x4 пикселя, то есть всего клеток 60х80. Правильно ли я понимаю, что если разрешение экрана будет 480х640, то одна клетка будет занимать 8х8 и количество клеток останется неизменным. Или же нужно оставить размер клетки 4х4 и их уже будет 120х160? Спасибо.

**Comment by thevery** [comment]
480х640 means that every cell will be 2x2 (and with 240x320 it will be 1x1)
