### ISSUE TITLE
Идея не видит AVD.

### ISSUE THREAD

**Issue by pgrachev** [IFMO-MobDev-2014/lesson1#31]
Android Studio отказывается видеть мой виртуальный Nexus, запиленный в Genymotion. Что делать? Может где-нибудь какие-нибудь пути прописать? Но где и какие?

**Comment by thevery** [comment]
Actually, no idea - linux?
Have you defined ADB path in genymotion settings?

**Comment by pgrachev** [comment]
Нет, семерка.

А зачем ABD пути как-то менять? Там вроде все по дефолту нормально работает. Прописал путь для Virtual Devices в папку, где пытается найти устройство Android Studio, но чего-то все равно ничего не работает. :(

В общем, спасите меня, я в отчаянии!

**Comment by thevery** [comment]
А сам эмулятор-то запущен? Незапущенный студия точно не видит.

**Comment by thevery** [comment]
Ну и genymotion для ADB - это USB device, а не emulator

**Comment by pgrachev** [comment]
Прописал пути для ABD, начал поставил галку USB Device. Все равно ничего не делает, выдавая "No Android facet found for app"

**Comment by thevery** [comment]
> No Android facet found for app

Так это точно не с эмулятором проблема.
можно запустить ./gradlew.bat installDebug из консоли

**Comment by pgrachev** [comment]
В какой ветке? Из какой консоли, из cmd?

**Comment by thevery** [comment]
Про ветку не понял, запускать из cmd

**Comment by pgrachev** [comment]
Ну в смысле в каталоге каком запускать?

**Comment by thevery** [comment]
В корневом каталоге проекта

**Comment by pgrachev** [comment]
![111](https://cloud.githubusercontent.com/assets/8770976/4273475/1eb57396-3ceb-11e4-8d3d-64a03722bd06.png)
Не знаю, что должно было произойти, произошло вот это.

**Comment by thevery** [comment]
17 строчку можно просто закомментить

**Comment by pgrachev** [comment]
SDK location not found. Я уже слабо понимаю что там нужно дефайнить

**Comment by pgrachev** [comment]
И все равно, я пока слабо понимаю как такая сборка поможет идее видеть эмулятор.

**Comment by thevery** [comment]
Нужно создать local.properties с примерно таким содержимым:
sdk.dir=/usr/local/opt/android-sdk

**Comment by thevery** [comment]
Проблема, повторюсь, не в эмуляторе, а в том, что идея (точно идея, а не студия) не может собрать проект.

**Comment by pgrachev** [comment]
А в каком виде создать local.properties? Это какой-то отдельный файл? Или какая-то строчка в какому-нибудь файле? Что это вообще?

**Comment by pgrachev** [comment]
Помогите мне, пожалуйста, у меня осталось 3.5 часа, а у меня еще даже проект не собирается в первоначальном виде.

**Comment by thevery** [comment]
Отдельный файл.
Попробуйте для начала сделать новый проект в android studio - от точно должен собираться и работать.

**Comment by pgrachev** [comment]
В смысле? Мне создать пустой проект и запустить?

**Comment by thevery** [comment]
Да. Собственно, это вы должны были сделать ещё на первой паре.

**Comment by pgrachev** [comment]
Ну не было у меня ноутбука на прошлой паре. Пустой проект работает, все в порядке.

**Comment by pgrachev** [comment]
При запуске того проекта, он почему-то просит "edit configuration".

**Comment by thevery** [comment]
Ну можно в пустой работающий проект переместить все нужные файлы поверх значит

**Comment by pgrachev** [comment]
Именно этим я сейчас и занимаюсь :)

**Comment by pgrachev** [comment]
Ну в общем я аккуратно переместил файлы, в итоге он начал падать с 

"Error:Execution failed for task ':app:preBuild'.

> failed to find target android-19 : P:\Android\sdk",

И снова требует от меня какой-то конфиг

**Comment by pgrachev** [comment]
По тому адресу все что нужно вроде лежало и лежит

**Comment by thevery** [comment]
android-19 - это версия используемого SDK, указана в build.gradle (`targetSdkVersion 19`)

**Comment by pgrachev** [comment]
у меня там >classpath 'com.android.tools.build:gradle:0.12.2'

**Comment by thevery** [comment]
это топлевел build.gradle, а нужно смотреть app/build.gradle

**Comment by pgrachev** [comment]
Я осилил! Можно час времени, пожалуйста?(
